name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "doc"


jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Run git checkout
      uses: actions/checkout@v4
    - name: Build README.md
      run: |
        make -C docs
    - name: Create PDF
      uses: BaileyJM02/markdown-to-pdf@v1
      with:
        input_path: docs/README.md
        output_dir: build
        images_dir: docs/images
        image_import: ./images
        build_html: false
        table_of_contents: false
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: README.pdf
        path: build/README.pdf
